### ISSUE TITLE
CPU版本的tensorflow是否可行？

### ISSUE THREAD

**Issue by Bismarrck** [JiangLiNSCC/TH2-demos#11]
参见：https://github.com/tensorflow/tensorflow/issues/110
原理上天河应该也可以部署纯CPU版本的tensorflow吧

**Comment by Bismarrck** [comment]
试了一下，bazel能安装，但是无法正常运行。看来目前还真没办法在天河上部署tensorflow。

**Comment by Bismarrck** [comment]
使用预编译的bazel需要GLIBC 2.17，正常安装bazel需要GLIBC 2.14和JDK 1.8，但是天河目前JDK 1.8和GLIBC 2.14冲突。

**Comment by lijiang2014** [comment]
感谢 @Bismarrck 的测试。
目前放弃在 RH6.5 环境下的 TF 安装尝试。
目前系统部有提供CentOS7 环境的节点，会在这些节点尝试安装TF ， 不过不会那么快进行。

**Comment by Bismarrck** [comment]
@lijiang2014 

有没有试过在天河上安装Anaconda？

我在我们自己的服务器上简单测试了一下，Anaconda版本的tensorflow似乎可以正常工作：
<img width="512" alt="screen shot 2016-12-04 at 9 18 15 am" src="https://cloud.githubusercontent.com/assets/719050/20863352/ec0db51a-ba02-11e6-8f2e-c8fb8ec5ea6b.png">

我们的系统：
```
(root) [chenxin@mu01 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.3 (Santiago)
(root) [chenxin@mu01 ~]$ uname -a
Linux mu01 2.6.32-431.29.2.el6.x86_64 #1 SMP Tue Sep 9 21:36:05 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
(root) [chenxin@mu01 ~]$
```

**Comment by lijiang2014** [comment]
@Bismarrck 
这个我之前试过，还是报 glibc 的错误：

`
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 60, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /WORK/app/TensorFlow/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so)


Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.
>>> 
`
你看下你的系统的 glibc 版本是不是升级过 ：

`
[nscc_ts_1@ln2%tianhe2-C bin]$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
[nscc_ts_1@ln2%tianhe2-C bin]$ 
`

目前天河是 2.12 的GLIBC , 可用 2.14 , 但更高的版本就会出问题

**Comment by Bismarrck** [comment]
很神奇啊，我看了一下我的系统，glibc依然是2.12，但是至少tensorflow的简单运算没什么问题。

<img width="682" alt="screen shot 2016-12-05 at 9 44 27 am" src="https://cloud.githubusercontent.com/assets/719050/20871326/8c666e90-bacf-11e6-8df0-ce7ed5658571.png">

**Comment by lijiang2014** [comment]
刚刚试了下 在 bcbio 分区 ， tensorflow 是可以使用的。（因为这个分区的 OS 版本比较高）
不过目前我不知道 bcbio 分区的规划。（是给大数据平台用的）
`
[nscc-gz_jiangli@cn13469%tianhe2-C bin]$ ipython
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import tensorflow as tf

In [2]: a = tf.constant(2.0)

In [3]: b = tf.constant(3.0)

In [4]: c = a + b 

In [5]: with tf.Session() as sess :
   ...:     print(sess.run(c))
   ...:     
5.0
`
这个系统的glibc 版本比较高 ：
[nscc-gz_jiangli@cn13469%tianhe2-C bin]$ ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
[nscc-gz_jiangli@cn13469%tianhe2-C bin]$

**Comment by Bismarrck** [comment]
@lijiang2014 那我们可以申请bcbio这个分区吗？

**Comment by lijiang2014** [comment]
嗯，这很奇怪啦。 那你这个  Anaconda 里面的  tensorflow 是怎么安装的 ？
我之前是直接用 pip 安装的，可以装上，但会有 glibc 的报错 。
编译安装则 感觉 bazel 装的有问题 。

**Comment by Bismarrck** [comment]
我是最简单的方式：

`conda install tensorflow`

Anaconda的预编译版本，tensorflow的版本号比较低，只有0.10rc0

**Comment by lijiang2014** [comment]
你发邮件给市场部门问问吧， 我觉得应该问题不大，你们也算是大数据相关的应用，大数据平台现在虽然还不完善，但试用应该没啥问题。

**Comment by lijiang2014** [comment]
Wow!　你的方法确实可行　，　我在　ln2  上也测试通过了 ： 

`
[nscc_ts_1@ln2%tianhe2-C bin]$ which python
/WORK/app/TensorFlow/anaconda2/bin/python
[nscc_ts_1@ln2%tianhe2-C bin]$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
>>> import tensorflow as tf
>>> a = tf.constant(2.0)
>>> b = tf.constant(3.0)
>>> c = a + b
>>> with tf.Session() as sess :
...     print(sess.run(c))
... 
5.0
`

**Comment by Bismarrck** [comment]
很神奇啊，也许是tensorflow 0.10对glibc的要求没那么高？或者是anaconda使用黑科技？

**Comment by lijiang2014** [comment]
看来pip 没有去正确的检测 glibc 的版本依赖，而 conda 自身的包管理器做到了 。。。
另外刚刚发现 其实上周同事已经装了一个 tensorflow :
`
[nscc-gz_jiangli@cn16356 ~]$ module avail tensorflow

----------------------------------------------- /WORK/app/modulefiles ------------------------------------------------
tensorflow/0.11.0
[nscc-gz_jiangli@cn16356 ~]$ module load tensorflow/0.11.0 
####################################################################
 To use TensorFlow you have to activate the conda environment by executing these two commands:
 1. settf
 2. source activate tensorflow_0_11_0
 
 (tensorflow)$  # Your prompt should change.
 # Run Python programs that use TensorFlow.
 # ...
 # When you are done using TensorFlow, deactivate the environment.
 (tensorflow)$ source deactivate tensorflow_0_11_0
####################################################################
[nscc-gz_jiangli@cn16356 ~]$ settf
[nscc-gz_jiangli@cn16356 ~]$ source activate tensorflow_0_11_0
(tensorflow_0_11_0) [nscc-gz_jiangli@cn16356 ~]$ 
(tensorflow_0_11_0) [nscc-gz_jiangli@cn16356 ~]$ python 
Python 2.7.12 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import tensorflow
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /WORK/app/CUDA/8.0/libnvvp:/WORK/app/CUDA/8.0/libnsight:/WORK/app/CUDA/8.0/lib64:/WORK/app/CUDA/8.0/lib:/WORK/app/cudnn/5.1-CUDA8.0/lib64:/WORK/app/gcc/4.9.2/lib64:/WORK/app/gcc/4.9.2/lib:/WORK/app/gcc/4.9.2/libexec:/WORK/app/mpc/0.8.1/lib:/WORK/app/MPFR/2.4.2/lib:/WORK/app/gmp/4.3.2/lib
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:160] hostname: cn16356
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:185] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] kernel reported version is: Permission denied: could not open driver version path for reading: /proc/driver/nvidia/version
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1080] LD_LIBRARY_PATH: /WORK/app/CUDA/8.0/libnvvp:/WORK/app/CUDA/8.0/libnsight:/WORK/app/CUDA/8.0/lib64:/WORK/app/CUDA/8.0/lib:/WORK/app/cudnn/5.1-CUDA8.0/lib64:/WORK/app/gcc/4.9.2/lib64:/WORK/app/gcc/4.9.2/lib:/WORK/app/gcc/4.9.2/libexec:/WORK/app/mpc/0.8.1/lib:/WORK/app/MPFR/2.4.2/lib:/WORK/app/gmp/4.3.2/lib
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1081] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
>>> import tensorflow as tf
>>> a = tf.constant(2.0)
>>> b = tf.constant(3.0)
>>> c = a + b
>>> with tf.Session() as sess :
...     print(sess.run(c))
... 
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_NO_DEVICE
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (cn16356): /proc/driver/nvidia/version does not exist
5.0
>>> exit
Use exit() or Ctrl-D (i.e. EOF) to exit
>>> exit()
(tensorflow_0_11_0) [nscc-gz_jiangli@cn16356 ~]$ 
`

**Comment by Bismarrck** [comment]
很好~cuDNN也装了啊，那我赶快去申请一下Tesla K80节点的试用权限。

**Comment by Bismarrck** [comment]
这个issue可以关闭了。
