### ISSUE TITLE
并行程序编译运行只能在超算内部云主机？

### ISSUE THREAD

**Issue by selfboot** [JiangLiNSCC/TH2-demos#14]
如果将eHPC 站点放到公网主机上，有没有办法将程序提交到超算，进行编译、运行？

**Comment by lijiang2014** [comment]
可以呀。
方案I ， 将将现在的后台服务绑定到一个公网IP .
方案II ， eHPC 通过VPN 连接天河系统。

**Comment by selfboot** [comment]
可以的话就很好了，方案1 实现起来难吗？

**Comment by lijiang2014** [comment]
后端服务绑定公网IP ， 实施起来不难，我刚刚已经测试了一下是没有问题的，不过会大大增加天河系统被网络攻击的风险。建议你们将公网的网站网址映射到云平台的IP上。这样能能避免迁移和HPC系统被攻击。

**Comment by lijiang2014** [comment]
我先关掉后端绑定公网IP，如果真的实在有这种需求，我这边也需要多加一些安全策略。

**Comment by selfboot** [comment]
映射到云平台的 IP 地址没问题，但是云平台上开放 80 端口比较麻烦，只能用其它端口。

所以目前吴老师想着用我们自己的服务器，开80端口，然后绑定专门申请的域名。

**Comment by lijiang2014** [comment]
了解了，我看看能不能通过使用跳板机的方案来权衡安全和公网访问 。

**Comment by selfboot** [comment]
👌
