### ISSUE TITLE
GPU 分区状态不可用及后续规划

### ISSUE THREAD

**Issue by lijiang2014** [JiangLiNSCC/TH2-demos#15]
* 目前TH2 HPC 系统原　普通用户的　ＧＰＵ 分区暂处于不可用状态。

* NSFCGZ　基金用户分区的　ＧＰＵ　分区正常使用（不过是比较老的卡　Ｍ２０５０　）。

* 普通用户的GPU分区规划将采用机架服务器重建，并且每个节点将配置两块性能强劲的 K80　，　以提供更加高性能和稳定的GPU环境。不过最近系统部工作比较繁忙,预计于三月上旬完成的重建可能会延期。分区可用后会在此再通知。

**Comment by Bismarrck** [comment]
在gpu分区完工之后能否安装tensorflow-1.0？

**Comment by lijiang2014** [comment]
@Bismarrck 现在有安装0.10.0rc0 和 0.11.0 ， 1.0 不知道能不能装上，到时候试试

**Comment by Bismarrck** [comment]
@lijiang2014 好的，原理上0.11可以的话，1.0应该完全也可以，1.0甚至可以通过pip安装，实在不行就用预编译好的呗。GPU分区什么时候上线，现在还没有消息吗？

**Comment by JiangLiNSCC** [comment]
最近系统部任务比较多，估计还很要一段时间






------------------


------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106035 （不推荐）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号






 

 
 
 
------------------ Original ------------------

**Comment by Bismarrck** [comment]
这次维护之后是不是GPU分区就能上线了？

**Comment by lijiang2014** [comment]
不是 ， 系统部最近一直没有人手来落实GPU分区的事，已经催过好几次了，如果维护完系统能稳定下来应该可以来做这个了 。

**Comment by lijiang2014** [comment]
# 通知
@Bismarrck 
GPU 分区现在开始准备上线了，现在透露点儿消息。
这次的 GPU 分区 采用完全独立的运行环境以提供高保障的服务，售价和使用方式也会与以往不同。
因为是独立环境，目前正在安装基础的软件环境： 编译器 和 MPI .
应用软件目前还没开始安装，~需要使用的用户现在起可以联系市场部了。（现在起可以试用）~
现阶段直接联系我吧（jiang.li@nscc-gz.cn）

**Comment by lijiang2014** [comment]
LN41 上的 TENSORFLOW 已经可以用了 。

BTW : 
```
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
```

这个提示谁知道怎么消除吗？

**Comment by Bismarrck** [comment]
@lijiang2014 这需要手动编译bazel和tensorflow。这个不重要，忽略即可。

**Comment by lijiang2014** [comment]
:rose:  谢了 ， 如果对性能影响不大我就不管了 ，现在来装 cuDNN 。

**Comment by Bismarrck** [comment]
@lijiang2014 scikit-learn、pandas等一些常用的数据分析的库能否也安装呢？

**Comment by lijiang2014** [comment]
没问题，需要哪些库在这里列给我吧，我先把 pandas 和 scikit-learn 装上

**Comment by Bismarrck** [comment]
@lijiang2014 能不能安装一下ipython呢

**Comment by JiangLiNSCC** [comment]
明天装下 
------------------ Original ------------------

**Comment by jx-zhong-for-academic-purpose** [comment]
您好，pytorch现在能在ln41上安装使用吗？

**Comment by lijiang2014** [comment]
@jx-zhong-for-academic-purpose 有需要的话我节后回去安装试试。如果还有其他需要配置的软件环境也请尽快说明。

**Comment by jx-zhong-for-academic-purpose** [comment]
@lijiang2014 谢谢您，您有空在搞这个，我至少1个月后才用，不急~

**Comment by lijiang2014** [comment]
@jx-zhong-for-academic-purpose  [PyTorch 目前已安装]( https://github.com/JiangLiNSCC/TH2-demos/wiki/Install-PyTorch-@-LN41)
