### ISSUE TITLE
天河二号上C调用matlab引擎失败Can't start Matlab engine!

### ISSUE THREAD

**Issue by johnfic** [JiangLiNSCC/TH2-demos#17]
在登录节点上尝试过运行，在kill之前是可以运行的，但是在计算节点上用engopen启动引擎失败，请问是怎么回事？

**Comment by lijiang2014** [comment]
请把详细的信息贴出来吧 ， 作业号 ， 使用的作业分区 （partition） , 提交作业所在的节点，具体的出错信息。

**Comment by johnfic** [comment]
就一个简单的启动matlab引擎的函数engOpen，在登录节点直接运行没事，提交到work和MIC节点上就输出Can't start Matlab engine!

if(!(ep=engOpen("matlab -nodesktop -nosplash"))){
        printf("Can't start Matlab engine!\n");
        exit(1);
 }

**Comment by lijiang2014** [comment]
**请使用 docker分区（docker_128） 使用 matlab**  。 work 分区 , MIC 分区 等普通分区的节点操作系统环境使用部分MATLAB 的功能时会出问题 。
