### ISSUE TITLE
ln41的caffe_cudnn有关问题

### ISSUE THREAD

**Issue by jx-zhong-for-academic-purpose** [JiangLiNSCC/TH2-demos#18]
1. 拷贝代码到自己文件夹，编译可以。但单元测试失败，make runtest 提示 Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version
2. 目前有没有可视化的界面？例如我在用caffe训练神经网络时，想用Python的matplotlib实时显示其损失函数下降图，怎么办？
3. 在ln0分区，怎么开docker分区，我的HOME下只有BIGDATA和WORKSPACE两个。。那个docker是在哪里？
谢谢您百忙中拨冗解答~

**Comment by lijiang2014** [comment]
@jx-zhong-for-academic-purpose 
1. 如果你是在登录节点make runtest 当然是会出错的， 登录节点没有GPU , CUDA 代码自然运行不了。
2. 没有可视化界面，不过我测试了 X 环境是可以用的，你可以一路X11 转发过去使用。
3. docker 是指SLURM的计算分区，即 yhinfo 命令看到的那些 ， 如ln41 上的gpu 分区。 而不是指 BIGDATA , WORKSPACE 那些文件系统分区。 一般的程序在其他作业分区可以正常跑就不需要使用docker 分区 。 docker 分区是在普通的计算分区的环境下再起了一个docker 环境来加载一个胖些的内核，来解决一些普通计算分区的问题（主要是JAVA 程序的支持），但docker 分区跑某些应用存在内存方面的问题，如果可以在普通分区运行的作业还是直接在普通分区运行比较好。
