### ISSUE TITLE
ORCA

### ISSUE THREAD

**Issue by Bismarrck** [JiangLiNSCC/TH2-demos#19]
您好，能否考虑在天河上安装ORCA[https://cec.mpg.de/orcadownload/index.php](url)

ORCA是德国马普研究所开发的一款量子化学计算程序，不开源但是可以免费使用

**Comment by lijiang2014** [comment]
您好，我刚看了下这个软件，似乎只给个人和课题组提供免费的LICENSE，提供的下载文件也是编译好的版本，您直接自己申请下载后上传应该就能够使用吧？
我也在试着下载一份，不过速度较慢，您那里有下载好的吗 ？

**Comment by Bismarrck** [comment]
我有下载好的，但是传不上去，我这边（丹麦）上传天河太慢了...

**Comment by lijiang2014** [comment]
哦哦 ， 那我下载好试着上传一份上去。

**Comment by Bismarrck** [comment]
Hi，请问有什么进展吗？我之前用过ORCA 3，只需要安装一套OpenMPI即可。ORCA 4用的好像是openmpi-2.0.2.

**Comment by lijiang2014** [comment]
@Bismarrck 放在了这里  /WORK/app/share/orca_4_0_0_2_linux_x86-64_openmpi202.tbz ， 你先自己试下吧。
