### ISSUE TITLE
天河二号单节点性能测试

### ISSUE THREAD

**Issue by yanqingphy** [JiangLiNSCC/TH2-demos#2]
yhbatch -N 1 -n 1 -c 1 -p evaluating ./elm_pb
elm_pb为可执行文件，按照测试提供的指导，这样提交任务，出现了错误
yhbatch: error: This does not look like a batch script.  The first
yhbatch: error: line must start with #! followed by the path to an interpreter.
yhbatch: error: For instance: #!/bin/sh
另外 -n 1 代表指定一个进程，不理解？

**Comment by JiangLiNSCC** [comment]
yhbatch 只能提交计算脚本，不能直接跟可执行程序；且如此错误提示所说的，脚本需要以#!/bin/bash 或 #!/bin/sh 开头 。
-n 1 表示指定一个进程， 用来运行串行程序。一般来说并不需要对yhbatch 指定 -n 参数 。 
更多信息可以查看：[天河二号资源管理系统使用手册](http://www.nscc-gz.cn/userfiles/files/[%E5%9F%BA%E9%87%91%E4%B8%93%E9%A1%B9%E6%95%99%E5%AD%A6%E8%B5%84%E6%96%99]-%E2%80%9C%E5%A4%A9%E6%B2%B3%E4%BA%8C%E5%8F%B7%E2%80%9D%E8%B5%84%E6%BA%90%E7%AE%A1%E7%90%86%E7%B3%BB%E7%BB%9F%E4%BD%BF%E7%94%A8%E5%85%A5%E9%97%A8.pdf)

**Comment by yanqingphy** [comment]
这个问题已解决，yhrun才是运行可执行文件，谢谢。
