### ISSUE TITLE
GPU计算结点与存储结点的数据通信问题

### ISSUE THREAD

**Issue by jiehuang008** [JiangLiNSCC/TH2-demos#20]
大家好，我们的算法分两部分，前端是MATLAB，后台是python(调用GPU进行计算)，计算过程中有中间文件生成，但是这些文件只是自用，不需要缓存到存储结点的磁盘上。但是实际情况是MATLAB生成的数据文件会先缓存到天河的存储结点上，然后python端再从存储结点读取进行处理，同理，python端生成的文件也会先缓存到存储结点上，再由MATLAB读取进行处理，这样一来一回通信开销很大，导致计算速度很慢，实际情况是我们生成的中间文件不大，GPU结点自带的内存完全够用，我想请问大家如何有没有遇到过类似情况的，如何让中间数据不存储到存储结点上而是存储到内存上？

欢迎交流~

**Comment by lijiang2014** [comment]
@jiehuang008 
你尝试下将中间文件的路径改为 写在 /tmp 下面或 /dev/shm 下面。
一般的节点是无盘系统，／tmp 和 /dev/shm 都是对应的内存。
不过GPU 分区的配置可能有所不同，需要你实际测试一下。

**Comment by jiehuang008** [comment]
已经测试过了，将中间文件路径改为/tmp或者/dev/shm的话不会报错，但是通信速度没有明显改善，而且比较奇怪的是，无论是哪个路径，都看不到生成的文件夹。。。，也就是说能工作，但是相应的日志文件以及中间数据从来都不出现。。。。

**Comment by jiehuang008** [comment]
貌似这两个路径对用户来说都是有读写和更改权限的（权限为777），但是为什么文件夹看不到呢？

**Comment by JiangLiNSCC** [comment]
文件夹看不到是什么意思 ？

**Comment by jiehuang008** [comment]
就是说本来在/tmp或者/dev/shm下应该会生成一个叫maxwell_server_files的文件夹，然后日志文件以及状态文件都会写在这下面，当然中间数据也会生成在下面，只不过计算完成后会删除掉（尽管中间数据最后会删除掉，但是日志和状态文件会一直在这个files文件夹下面，一个算例计算完成以后，大概有几百兆的样子），奇怪的是现在maxwell_server_files这个文件夹都生成不了，但是它竟然不报错。。。

**Comment by lijiang2014** [comment]
你是登录到计算节点去查看的吗 ？
这些内存映射的文件夹不是共享存储，在每个节点上是不同的。如果你想检查这些文件的状态，需要在计算过程中登录到对应的计算节点去查看。 
速度的话需要测试实际的数据来进行评估。
要进行性能分析和优化，要先进行性能分析，获得各个部分的耗时以及其随并行规模的变化。
你计算的数据量是可以调节的吗？你可以测测弱可扩展性如何。
如果没有设置上的问题，你之前的测试表明目前的强可扩展性比较差。

**Comment by jiehuang008** [comment]
您好！
1、登录到计算结点查看中间文件是有的，没问题，之前是简单的用文件管理系统看，所以没看到。
2、用相同的算例对中间文件在不同位置时进行了测试，通信速度基本没区别（均比本地慢。
3、计算的数据量不同的算例不一样。
4、是任务结束了，生成在内存上的日志文件和状态文件就会释放吗？
5、不太清楚您所说的弱可扩展性和强可扩展性的意思？

**Comment by JiangLiNSCC** [comment]
4、是任务结束了，生成在内存上的日志文件和状态文件就会释放吗？
是的 ， 计算节点会进行清理，释放资源以让下一个任务能正常使用所有资源
5、不太清楚您所说的弱可扩展性和强可扩展性的意思？
以你的算例为例子，
测试 1 ， 数据量 100 MB ， 1 GPU 
测试 2， 数据量 100 MB ， 2 GPU 

测试 3， 数据量 100 MB ， 4 GPU 

测试 4 ， 数据量 200 MB ， 2 GPU 
测试 5， 数据量 400 MB ， 4 GPU 



测试 1,2,3 得到的并行特征是强可扩展性的特征


测试 1,4,5 得到的并行特征是弱可扩展性的特征



大部分算法都有合适的数据规模（不同硬件下不同）， 太低或太高性能都不能充分发挥，要通过测试得到合适的规模（并行规模和数据规模）




------------------
------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106042 （不推荐  2017/5/8 更新）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号
 

 
 
 
------------------ Original ------------------

**Comment by jiehuang008** [comment]
1、测试了下文件是否会释放的问题，结果表明，没有释放（刚好两次提交任务都分配了同一个节点），我不知道别的用户登录到该节点以后会不会自动释放。。。

**Comment by lijiang2014** [comment]
这个不是很严重的问题，/tmp 是临时目录，系统会定时清理，节点清理程序也会去清理，不过可能是根据用量来判断的。

**Comment by jiehuang008** [comment]
貌似MATLAB在HPC上会发生一些莫名的问题，我咨询了下我们这边计算机学院关于通信速度慢的事情，它们说如果同一个版本在本地和天河区别很大的话，软件本身应该是没有问题的，极有可能是结点架构和通信方式的问题。。。

**Comment by lijiang2014** [comment]
这个是实现策略的问题，MATLAB 是为本地机设计的，IO 和 并行的模式都是针对个人电脑或工作站的，系统环境也是针对最新的系统环境。而HPC 架构比较复杂，系统环境的更新换代也不会太快。

**Comment by jiehuang008** [comment]
是的，他们也提出让我们把代码全都改成python或者C，但是这个工作量非常大，时间成本太高，而且据说MATLAB本身对多线程的支持很弱？如果不重写代码的话，他们提出了两个方案：
1、放在天河的云计算平台上，但是云平台又没有GPU结点。
2、像阿里一样，从HPC上映射一个个人计算集群（据他们说技术上这是可行的）。

**Comment by JiangLiNSCC** [comment]
1. 如果是包节点自己插卡是可以的，我们现在没有多余的卡
2.其实解决不了问题，反而由于多了一个虚拟化的层次会更慢

3.你可以进行一个尝试，占住一个计算节点，将整个MATLAB 拷贝到 /tmp 下去执行，看看会不会好些 。个人觉得还是MATLAB 和 lustre 文件系统之间的问题。

**Comment by jiehuang008** [comment]
把所有程序都放在/dev/shm下进行了测试，通信速度基本没变化，/tmp没试，估计是一样的，这么看来有可能是因为matlab本身是装在bigdata下面的，与计算结点完全分开了。

**Comment by lijiang2014** [comment]
"""When you move to starting and running MATLAB from the NFS server, the application starts and runs over NFS. NFS can be pretty good at this, using caching and other tricks to make it better -- but it's still not the same as running from local disks in most cases, startup will likely be slower, as will accessing "new" things""" ----[MATLAB Answers](https://cn.mathworks.com/matlabcentral/answers/48143-my-matlab-mdcs-worker-slower)
