### ISSUE TITLE
GPU节点是否支持可视化连接？

### ISSUE THREAD

**Issue by guanshuosen** [JiangLiNSCC/TH2-demos#22]
您好，请问高性能计算 [K80 GPU节点](http://www.nscc-gz.cn/Product/HighPerformanceComputingService/ServiceCharacteristics.html?)是否支持可视化远程连接？可以的话，具体怎么操作？

谢谢～

**Comment by lijiang2014** [comment]
k80 是用作计算的gpu , 非图像渲染的显卡。
如果你的可视化需求是常用的前后处理软件，建议使用天河星光的可视化环境。

**Comment by guanshuosen** [comment]
@lijiang2014 我是基于深度学习（tensorflow, Cuda）做图像处理的，所以也是用GPU来运算，只是我想有些地方还可能用到MATLAB，所以想远程可视化操作，这样支持吗？

**Comment by JiangLiNSCC** [comment]
K80 的节点目前不直接支持可视化。








------------------
------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106042 （不推荐  2017/5/8 更新）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号
 

 
 
 
------------------ Original ------------------

**Comment by guanshuosen** [comment]
@JiangLiNSCC 谢谢～  那像我这样的情况（需要用GPU做图像处理又需要远程可视化操作的），应该选择什么方案比较合适？ 是使用天河星云吗？还是要另外申请云平台的虚拟机？不过咨询那边说云平台虚拟机不支持显卡运算

**Comment by JiangLiNSCC** [comment]
你在GPU 分区计算，算完了用天河星光看就行了








------------------
------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106042 （不推荐  2017/5/8 更新）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号
 

 
 
 
------------------ Original ------------------

**Comment by guanshuosen** [comment]
@JiangLiNSCC  好的，非常感谢～
