### ISSUE TITLE
Mathematica的安装

### ISSUE THREAD

**Issue by joebradly** [JiangLiNSCC/TH2-demos#23]
你好！我在天河二号自己的用户下安装了mathematica, 进行了激活。在登录节点上mathematica是可以
运行的。如下：
[xxxxx@ln1%tianhe2-C ~]$ math -run < test_mathematica.m 
Mathematica 11.1.1 Kernel for Linux x86 (64-bit)
Copyright 1988-2017 Wolfram Research, Inc.

In[1]:= 
Out[1]= 5050

In[2]:= 
        149
Out[2]= ---
         6

In[3]:= 
        30449
Out[3]= -----
          6**
然后我将上面的运算通过脚本提交之后，出来了如下的输出
**Mathematica 11.1.1 Kernel for Linux x86 (64-bit)                   
Copyright 1988-2017 Wolfram Research, Inc.                         

Mathematica cannot find a valid password.                          

For automatic Web Activation enter your activation key             
(enter return to skip Web Activation):                             
You will need to get a password from your                          
license certificate or from Wolfram Research                       
(http://register.wolfram.com).   
Machine name:   cn5755           
MathID: 6520-23869-64467         

You will need a valid activation key and password in order         
to proceed. Go to http://user.wolfram.com to                       
register your activation key and obtain the password.              

Enter your Activation key [format xxxx-xxxx-xxxxxx]:               
Enter your password:             
The password you entered is not valid.                             
Please press Enter to quit.**
请问这个是什么原因呢？谢谢！

**Comment by JiangLiNSCC** [comment]
在其他登录节点上可以正常运行吗？ 




------------------
------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106042 （不推荐  2017/5/8 更新）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号
 

 
 
 
------------------ Original ------------------

**Comment by joebradly** [comment]
@JiangLiNSCC 
我ssh 到其它登录节点也是可以运行的。但是就是通过yhbatch提交的时候不行。是由于进行的是单机版的激活吗？但是破解的matlab却是在天河2号上运行的很好。

**Comment by JiangLiNSCC** [comment]
可能和你绑定的网卡有关， 计算节点只有高速网能访问，而登录节点网段比较多。 






------------------
------------------------------
* 典型性问题欢迎到下面的网址进行提问和搜索 ！
* https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
* Links : docs 搜索已有问题  提新问题
* 办公时间可联系： 020-37106042 （不推荐  2017/5/8 更新）
* 李江  国家超级计算广州中心/广州超级计算中心/应用部
* 广州市番禺区大学城外环东路132号
 

 
 
 
------------------ Original ------------------

**Comment by joebradly** [comment]
不好意思，我没理解这为什么会跟网卡有关呢？

2017-08-15 18:07 GMT+08:00 Jiang Li <notifications@github.com>:

**Comment by qenb** [comment]
我刚刚也在天河二号自己文件夹里安装了mathematica，试图用yhbatch提交wolframscript脚本时遇到了同样的问题。如果有谁解决了的话请务必赐教。

**Comment by lijiang2014** [comment]
@qenb mathematica 您是在登录节点安装的吗？ 安装过程中需要设置网卡MAC地址之内的吗？ 如果有相关的设置，记得选择gn 网络的网卡地址来生成 License

**Comment by qenb** [comment]
> @qenb mathematica 您是在登录节点安装的吗？ 安装过程中需要设置网卡MAC地址之内的吗？ 如果有相关的设置，记得选择gn 网络的网卡地址来生成 License

安装时没有网卡设置的相关选项。
但是安装时的激活文件是由mathID（由计算机硬件生成，类似于电脑的产品编号）确定的，请问我的问题会与这个有关吗？

**Comment by lijiang2014** [comment]
@qenb  会的，你可以咨询一个 mathematica 公司， 在有多块网卡的机器上生成 mathID 时如何选择特定的网卡，而非默认的 eth0的相关信息

**Comment by qenb** [comment]
> @qenb 会的，你可以咨询一个 mathematica 公司， 在有多块网卡的机器上生成 mathID 时如何选择特定的网卡，而非默认的 eth0的相关信息

好的，谢谢！
