### ISSUE TITLE
Git 远程仓库

### ISSUE THREAD

**Issue by MerlinPendragon** [JiangLiNSCC/TH2-demos#24]
我在天河2号上面有一个远程仓库，想和我本地的仓库保持同步，但是没有权限，能申请权限吗？

> debug1: Reading configuration data /Users/***/.ssh/config
> debug1: /Users/***/.ssh/config line 35: Applying options for gzcs
> debug1: Reading configuration data /etc/ssh/ssh_config
> debug1: /etc/ssh/ssh_config line 53: Applying options for *
> debug1: Connecting to 172.16.22.11 [172.16.22.11] port 22.
> debug1: Connection established.
> debug1: key_load_public: No such file or directory
> debug1: identity file /Users/%KeyDir%/%IdentityFile% type -1
> debug1: key_load_public: No such file or directory
> debug1: identity file /Users/%KeyDir%/%IdentityFile%-cert type -1
> debug1: Enabling compatibility mode for protocol 2.0
> debug1: Local version string SSH-2.0-OpenSSH_7.4
> debug1: Remote protocol version 2.0, remote software version OpenSSH_5.3
> debug1: match: OpenSSH_5.3 pat OpenSSH_5* compat 0x0c000000
> debug1: Authenticating to 172.16.22.11:22 as 'git'
> debug1: SSH2_MSG_KEXINIT sent
> debug1: SSH2_MSG_KEXINIT received
> debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
> debug1: kex: host key algorithm: ssh-rsa
> debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
> debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
> debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(2048<3072<8192) sent
> debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
> debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
> debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
> debug1: Server host key: ssh-rsa SHA256:8OVFevV4Qv+vNon9S1Yityp93kEoa0N2QN3A7VunDdE
> The authenticity of host '172.16.22.11 (172.16.22.11)' can't be established.
> RSA key fingerprint is SHA256:8OVFevV4Qv+vNon9S1Yityp93kEoa0N2QN3A7VunDdE.
> Are you sure you want to continue connecting (yes/no)? yes
> Warning: Permanently added '172.16.22.11' (RSA) to the list of known hosts.
> debug1: rekey after 4294967296 blocks
> debug1: SSH2_MSG_NEWKEYS sent
> debug1: expecting SSH2_MSG_NEWKEYS
> debug1: SSH2_MSG_NEWKEYS received
> debug1: rekey after 4294967296 blocks
> debug1: SSH2_MSG_SERVICE_ACCEPT received
> debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
> debug1: Next authentication method: publickey
> debug1: Trying private key: /Users/%KeyDir%/%IdentityFile%
> debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic
> debug1: No more authentication methods to try.
> Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
>

**Comment by JiangLiNSCC** [comment]
请问需要什么样的权限？

如果是要配置 ssh_conf , 你可以在你的 ~/.ssh 下面创建一个 conf 文件进行配置（ cat /etc/ssh/ssh_conf > ~/.ssh/conf ） , /etc/ssh/ssh_conf 是全局配置，不允许修改。

**Comment by MerlinPendragon** [comment]
我 ssh 连天河没问题，就是我在本机把天河上的 git 仓库 pull 下来的时候

> git remote add gzcs git@gzcs:$gzdir/epoch-xb/epoch2d/post.git
> git pull gzcs master

说没有权限... 

> Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.

**Comment by lijiang2014** [comment]
* 天河并没有对外提供git 服务。虽然登录节点上有git 程序，但VPN 是进行了IP 和端口限制的，应该是无法直接访问的。而且由于这方面的网络限制，目前也无法提供这种服务。

*  你在天河上也没有 git 这样一个账户，你这种用法是个人电脑的用法， 所以会抱权限的错误。
