### ISSUE TITLE
matlab2017b 运行报错“Could not load a transcoding service” 

### ISSUE THREAD

**Issue by cangyou** [JiangLiNSCC/TH2-demos#26]
你好，我在天河2 中安装了matlab 2017b (包括production service)， 安装后也按教程配置了。但在运行的时候，显示“Could not load a transcoding service”。 不知是什么原因呢？
谢谢！

**Comment by lijiang2014** [comment]
请见 #25 ；

另外我未曾安装使用过 2017B 版本的 MATLAB，可能存在系统兼容性问题。
