### ISSUE TITLE
天河二号可以同时打开多少个终端？

### ISSUE THREAD

**Issue by yanqingphy** [JiangLiNSCC/TH2-demos#3]
天河二号上多个人同时用一个账号，可以同时打开多少个终端？或者多少人可以同时登陆一个账号？

**Comment by JiangLiNSCC** [comment]
Linux 本身是支持多用户登录，没有连接数的限制的。
但是VPN 账号有连接数的限制，如果连接数不够用，可以向我们申请增加。

--- 无论回答有没有解决您的问题，请给出反馈信息。

**Comment by yanqingphy** [comment]
好吧，有时候登录天河经常掉线了，可能是网络原因。三个人用，应该登录VPN连接数是够用的。

**Comment by JiangLiNSCC** [comment]
面对这种情况，你可以学习一下使用 LINUX 的 [screen](https://www.ibm.com/developerworks/cn/linux/l-cn-screen) 命令 ，不过注意自己管理好screen , 还是蛮占服务器资源的。

--- 无论回答有没有解决您的问题，请给出反馈信息。

**Comment by yanqingphy** [comment]
这命令比较复杂，尝试着用，嘿嘿，Thanks

**Comment by JiangLiNSCC** [comment]
此问题已解决。
