### ISSUE TITLE
天河二号登录不上，即使登录上了，vi,cd,:wq等基本操作很卡，怎么办？

### ISSUE THREAD

**Issue by yanqingphy** [JiangLiNSCC/TH2-demos#5]
本地网速很好，但天河二号仍登录不上，即使登录上了，vi,cd,:wq等基本操作很卡，这是怎么回事，有没有快捷方法解决这个问题？

**Comment by JiangLiNSCC** [comment]
这种问题可能有很多原因，有的时候是系统负载问题，有的时候是系统有些小BUG。
简而言之的解决办法： 
- 换个登陆节点试试
- 所有的登陆节点都不行，联系我们告知详情，等待恢复。

可能的原因：
文件系统 ， 可以用 df 检查 ， 可能只是某个ln 的挂载问题，也可能是文件系统自身故障。
LN 负载太高 ， 可以用 top ， free 等命令来检查登录节点的cpu / MEMORY 负载；如果某个登录节点负载太高了，也会使操作太卡。
其他原因 ， 欢迎补充。

**Comment by JiangLiNSCC** [comment]
另外今天下午5：00 系统要停机维护两天，不要忘了哈。

**Comment by yanqingphy** [comment]
登录到ln0，NSFC分区进不了，写文件仍然会出现问题。
"data/BOUT.inp" E667: Fsync failed
Press ENTER or type command to continue

**Comment by JiangLiNSCC** [comment]
忘了你是基金用户了 , 前面的节点时给用普通用户用的。。 
NSFCGZ 文件系统出了点小问题，在进行恢复。

**Comment by yanqingphy** [comment]
哦哦，好吧，静等你们搞好了，哈哈，Thanks

**Comment by JiangLiNSCC** [comment]
@yanqingphy  现在应该OK 了。

**Comment by yanqingphy** [comment]
试了下，可以了，Thanks
