### ISSUE TITLE
长期开放性讨论

### ISSUE THREAD

**Issue by JiangLiNSCC** [JiangLiNSCC/TH2-demos#7]
在此您可以讨论任何事儿

**Comment by Bismarrck** [comment]
您好，能给GPU分区的Python (3.6.1, 2.7.x)安装一下ase这个包吗？

https://wiki.fysik.dtu.dk/ase/index.html

**Comment by lijiang2014** [comment]
@Bismarrck  source /BIGDATA/app/ASC/venv-py2.7/bin/activate

**Comment by Bismarrck** [comment]
非常感谢！

**Comment by Bismarrck** [comment]
请问，TensorFlow能否升级？比如升级到1.3.0，目前天河上还是1.0.1

**Comment by lijiang2014** [comment]
好的，我下周试下装下1.3。

**Comment by jx-zhong-for-academic-purpose** [comment]
您好，我想用THUMOS14和ActivityNet的视频数据集在TianHe2训练神经网络，但数据集约300G，从我的PC传过去超算，总是断了连接，请问该怎么办？？

**Comment by Bismarrck** [comment]
@jx-zhong-for-academic-purpose 分割成多个几G大小的包慢慢scp上去试试？

**Comment by lijiang2014** [comment]
@jx-zhong-for-academic-purpose 这种情况可以寄盘过来拷贝，详细你联系 @hliang 吧。

**Comment by jx-zhong-for-academic-purpose** [comment]
@lijiang2014 好的，谢谢！

**Comment by Bismarrck** [comment]
@lijiang2014 TensorFlow从1.0.1到现在的1.3可谓有了巨大的提升，很多1.0的api已经不能用了，所以我现在必须等你们装1.3.0。另外，希望也能安装一个官方的[ase](https://wiki.fysik.dtu.dk/ase/index.html)

**Comment by lijiang2014** [comment]
@Bismarrck  目前1.3版本已经安装测试完毕了。ASE 没什么其他人用，我就直接也装到这个Python环境了。  即GPU 环境的TensorFlow/1.3-gpu-py3.6 和。TensorFlow/1.3-gpu-py2.7 .

我现在换部门了，这个任务中间拖沓了一下，比较晚弄好，见谅。

**Comment by Bismarrck** [comment]
@lijiang2014 非常感谢！
