### ISSUE TITLE
天河二号登录docker分区怎么需要密码了

### ISSUE THREAD

**Issue by yanqingphy** [JiangLiNSCC/TH2-demos#8]
[nsfc2015_488@ln7%tianhe2-E ~]$ ssh -X cn7552
nsfc2015_488@cn7552's password: 
是不是还在维护当中

**Comment by JiangLiNSCC** [comment]
系统恢复过来有些地方有些小问题。这个问题现在正在修复。

---

---
- 典型性问题欢迎到下面的网址进行提问和搜索 ！
- https://github.com/JiangLiNSCC/TH2-demos/issues （推荐）
- Links : docs 搜索已有问题  提新问题
- 办公时间可联系： 020-37106035 （不推荐）
- 李江  国家超级计算广州中心/广州超级计算中心/应用部
- 广州市番禺区大学城外环东路132号

------------------ Original ------------------

**Comment by yanqingphy** [comment]
OK,Thanks

**Comment by JiangLiNSCC** [comment]
@yanqingphy 刚刚测试了一下，已经可以了。

**Comment by yanqingphy** [comment]
可以了，一切都正常了。
